name: Node.js CI
'on':
  push:
    branches:
      - master
      - beta
      - renovate/**
  pull_request:
    types:
      - opened
      - synchronize
env:
  FORCE_COLOR: 1
  NPM_CONFIG_COLOR: always
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm
      - name: Setup node
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}
      - uses: bahmutov/npm-install@c46e3830503dcb831cf4aee3f26b4e6bce8cc9d2 # v1.8.35
      - run: npm test
  trigger-release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: verify
    steps:
      - uses: octokit/request-action@v2.x
        with:
          route: >-
            POST
            /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches
          owner: traverson
          repo: commitlint-config-traverson
          ref: ${{ github.ref }}
          workflow_id: release.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
